git:
  depth: 1

before_install:
  - sudo apt-get install graphicsmagick

language: ruby

install:
  - bundle install

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production

script:
  - echo "${TRAVIS_COMMIT}" > version
  - bundle exec jekyll build --baseurl /robotka.robotickytabor.cz/

cache: bundler

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local-dir: _site
  on:
    branch: master
