name: Github pages deploy
on:
  push:
    branches: [master]
env:
  JEKYLL_ENV: "production"
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Install graphicsmagick
        run: sudo apt-get install graphicsmagick libxml2 libxslt1.1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Not needed with a .ruby-version file
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Add version
        run: echo "${GITHUB_SHA}" > version
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Generate
        run: bundle exec jekyll build
      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_PAT }}
          BRANCH: gh-pages
          FOLDER: _site
          REPOSITORY_NAME: RoboticsBrno/robotka.robotickytabor.cz-ghpages
          SINGLE_COMMIT: true
